### ISSUE TITLE
Run Time exception

### ISSUE THREAD

**Issue by sealover06** [lentschi/cordova-plugin-autostart#1]
Hello, trying to use your plugin, on a Tablet, Android 6.0.1 

I'm getting : 

07-20 16:11:36.928  6027  6027 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.tonikorin.cordova.plugin.autostart.BootCompletedReceiver: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1

my simple code :  

var myTextArea='';

var app = {
    initialize: function() { this.bindEvents(); },
    bindEvents: function() { document.addEventListener('deviceready', this.onDeviceReady, false); },
    onDeviceReady: function() { main(); }
};

app.initialize();

function main() { 
	myPrint('> AST: AutoStart Test / main()');
	cordova.plugins.autoStart.enable();
	myPrint('<< main()');
}
function $(id){return document.getElementById(id);}
function myPrint(str){ myTextArea+=str+'\n'; $('id-textarea').innerHTML = myTextArea; } 

Thanks a lot in advance.

**Comment by lentschi** [comment]
@sealover06 I'm afraid you've posted on the wrong page. This is just a project specific fork and it is by no means up to date.
So I suggest you check the issues at https://github.com/ToniKorin/cordova-plugin-autostart/issues and create your own there if your problem hasn't been described yet. :wink:

**Comment by sealover06** [comment]
ok, sorry, thanks ! ;-)
